export const APPLICATION_MOBILE_MENU_OPEN = 'APPLICATION:MOBILE_MENU:OPEN'
export const APPLICATION_MOBILE_MENU_CLOSED = 'APPLICATION:MOBILE_MENU:CLOSED'

export const APPLICATION_PRELUDIUM = 'APPLICATION_PRELUDIUM'
export const APPLICATION_INITIALIZED = 'APPLICATION:INITIALIZED'
export const APPLICATION_READY = 'APPLICATION:READY'
export const APPLICATION_RESIZE = 'APPLICATION:RESIZE'
export const APPLICATION_SCROLL = 'APPLICATION:SCROLL'
export const APPLICATION_VISIBILITY_CHANGE = 'APPLICATION:VISIBILITY_CHANGE'
